### ISSUE TITLE
Task fails - cannot find directory

### ISSUE THREAD

**Issue by alanshortis** [jon301/grunt-modernizr-builder#1]
When packages have been installed using NPM v3.3.12 with a flat file tree, I get the following error:

`[...]node_modules/grunt-modernizr-builder/node_modules/.bin/modernizr: No such file or directory`.

I changed line 16 in `modernizr_builder.js` to point to the equivalent location: `var cmd = [path.join(__dirname, '..', '..', '.bin', 'modernizr')];`.

This throws a different error: `TypeError: _.findWhere is not a function`.

**Comment by brianmcallister** [comment]
I was able to hack in a fix by changing line 16 to `var cmd = [path.join(__dirname, '..', '..', 'modernizr', 'bin', 'modernizr')];`, but I don't think I know enough about how `npm` works to know for sure that the `modernizr` directory will always be in `node_modules` because this package defined it as a dependency.

**Comment by jon301** [comment]
Hi guys,

Thank you for your feedbacks, this issue should be fixed now. Please pull the latest version (v0.1.8).

Tested with npm 2 & 3
